#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mise.Inventory.Android.Resource", IsApplication=true)]

namespace Mise.Inventory.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Mindscape.Raygun4Net.Xamarin.Android.Resource.String.library_name = global::Mise.Inventory.Android.Resource.String.library_name;
			global::ModernHttpClient.Resource.String.library_name = global::Mise.Inventory.Android.Resource.String.library_name;
			global::PCLCrypto.Resource.String.ApplicationName = global::Mise.Inventory.Android.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::Mise.Inventory.Android.Resource.String.Hello;
			global::Splat.Resource.String.library_name = global::Mise.Inventory.Android.Resource.String.library_name;
			global::Stripe.Resource.Drawable.amex = global::Mise.Inventory.Android.Resource.Drawable.amex;
			global::Stripe.Resource.Drawable.credit = global::Mise.Inventory.Android.Resource.Drawable.credit;
			global::Stripe.Resource.Drawable.cvc = global::Mise.Inventory.Android.Resource.Drawable.cvc;
			global::Stripe.Resource.Drawable.diners = global::Mise.Inventory.Android.Resource.Drawable.diners;
			global::Stripe.Resource.Drawable.discover = global::Mise.Inventory.Android.Resource.Drawable.discover;
			global::Stripe.Resource.Drawable.jcb = global::Mise.Inventory.Android.Resource.Drawable.jcb;
			global::Stripe.Resource.Drawable.maestro = global::Mise.Inventory.Android.Resource.Drawable.maestro;
			global::Stripe.Resource.Drawable.mastercard = global::Mise.Inventory.Android.Resource.Drawable.mastercard;
			global::Stripe.Resource.Drawable.visa = global::Mise.Inventory.Android.Resource.Drawable.visa;
			global::Stripe.Resource.Id.stripeCvc = global::Mise.Inventory.Android.Resource.Id.stripeCvc;
			global::Stripe.Resource.Id.stripeExpiration = global::Mise.Inventory.Android.Resource.Id.stripeExpiration;
			global::Stripe.Resource.Id.stripeImage = global::Mise.Inventory.Android.Resource.Id.stripeImage;
			global::Stripe.Resource.Id.stripeLastFour = global::Mise.Inventory.Android.Resource.Id.stripeLastFour;
			global::Stripe.Resource.Id.stripeLayoutOne = global::Mise.Inventory.Android.Resource.Id.stripeLayoutOne;
			global::Stripe.Resource.Id.stripeLayoutTwo = global::Mise.Inventory.Android.Resource.Id.stripeLayoutTwo;
			global::Stripe.Resource.Id.stripeNumber = global::Mise.Inventory.Android.Resource.Id.stripeNumber;
			global::Stripe.Resource.Layout.stripeviewlayout = global::Mise.Inventory.Android.Resource.Layout.stripeviewlayout;
			global::Stripe.Resource.String.library_name = global::Mise.Inventory.Android.Resource.String.library_name;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::Mise.Inventory.Android.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::Mise.Inventory.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int amex = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int credit = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cvc = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int diners = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int discover = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int jcb = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int launcher = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int maestro = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int mastercard = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int mise = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int restaurantLoading = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int splashscreen = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int StockboyLaunch = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int visa = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int stripeCvc = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int stripeExpiration = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int stripeImage = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int stripeLastFour = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int stripeLayoutOne = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int stripeLayoutTwo = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int stripeNumber = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int stripeviewlayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int App_Theme = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Splash_Theme = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int _AppTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
