//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Mise.Inventory.Android.MercuryWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HCServiceSoap", Namespace="http://www.mercurypay.com/")]
    public partial class HCService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InitializePaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcknowledgePaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitializeCardInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyCardInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcknowledgeCardInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadCSSOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadCSSOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveCSSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HCService() {
            this.Url = "https://hc.mercurydev.net/hcws/hcservice.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InitializePaymentCompletedEventHandler InitializePaymentCompleted;
        
        /// <remarks/>
        public event VerifyPaymentCompletedEventHandler VerifyPaymentCompleted;
        
        /// <remarks/>
        public event AcknowledgePaymentCompletedEventHandler AcknowledgePaymentCompleted;
        
        /// <remarks/>
        public event InitializeCardInfoCompletedEventHandler InitializeCardInfoCompleted;
        
        /// <remarks/>
        public event VerifyCardInfoCompletedEventHandler VerifyCardInfoCompleted;
        
        /// <remarks/>
        public event AcknowledgeCardInfoCompletedEventHandler AcknowledgeCardInfoCompleted;
        
        /// <remarks/>
        public event UploadCSSCompletedEventHandler UploadCSSCompleted;
        
        /// <remarks/>
        public event DownloadCSSCompletedEventHandler DownloadCSSCompleted;
        
        /// <remarks/>
        public event RemoveCSSCompletedEventHandler RemoveCSSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/InitializePayment", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InitPaymentResponse InitializePayment(InitPaymentRequest request) {
            object[] results = this.Invoke("InitializePayment", new object[] {
                        request});
            return ((InitPaymentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void InitializePaymentAsync(InitPaymentRequest request) {
            this.InitializePaymentAsync(request, null);
        }
        
        /// <remarks/>
        public void InitializePaymentAsync(InitPaymentRequest request, object userState) {
            if ((this.InitializePaymentOperationCompleted == null)) {
                this.InitializePaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializePaymentOperationCompleted);
            }
            this.InvokeAsync("InitializePayment", new object[] {
                        request}, this.InitializePaymentOperationCompleted, userState);
        }
        
        private void OnInitializePaymentOperationCompleted(object arg) {
            if ((this.InitializePaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializePaymentCompleted(this, new InitializePaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/VerifyPayment", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PaymentInfoResponse VerifyPayment(PaymentInfoRequest request) {
            object[] results = this.Invoke("VerifyPayment", new object[] {
                        request});
            return ((PaymentInfoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyPaymentAsync(PaymentInfoRequest request) {
            this.VerifyPaymentAsync(request, null);
        }
        
        /// <remarks/>
        public void VerifyPaymentAsync(PaymentInfoRequest request, object userState) {
            if ((this.VerifyPaymentOperationCompleted == null)) {
                this.VerifyPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyPaymentOperationCompleted);
            }
            this.InvokeAsync("VerifyPayment", new object[] {
                        request}, this.VerifyPaymentOperationCompleted, userState);
        }
        
        private void OnVerifyPaymentOperationCompleted(object arg) {
            if ((this.VerifyPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyPaymentCompleted(this, new VerifyPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/AcknowledgePayment", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AcknowledgePayment(PaymentInfoRequest request) {
            object[] results = this.Invoke("AcknowledgePayment", new object[] {
                        request});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AcknowledgePaymentAsync(PaymentInfoRequest request) {
            this.AcknowledgePaymentAsync(request, null);
        }
        
        /// <remarks/>
        public void AcknowledgePaymentAsync(PaymentInfoRequest request, object userState) {
            if ((this.AcknowledgePaymentOperationCompleted == null)) {
                this.AcknowledgePaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcknowledgePaymentOperationCompleted);
            }
            this.InvokeAsync("AcknowledgePayment", new object[] {
                        request}, this.AcknowledgePaymentOperationCompleted, userState);
        }
        
        private void OnAcknowledgePaymentOperationCompleted(object arg) {
            if ((this.AcknowledgePaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcknowledgePaymentCompleted(this, new AcknowledgePaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/InitializeCardInfo", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InitCardInfoResponse InitializeCardInfo(InitCardInfoRequest request) {
            object[] results = this.Invoke("InitializeCardInfo", new object[] {
                        request});
            return ((InitCardInfoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void InitializeCardInfoAsync(InitCardInfoRequest request) {
            this.InitializeCardInfoAsync(request, null);
        }
        
        /// <remarks/>
        public void InitializeCardInfoAsync(InitCardInfoRequest request, object userState) {
            if ((this.InitializeCardInfoOperationCompleted == null)) {
                this.InitializeCardInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeCardInfoOperationCompleted);
            }
            this.InvokeAsync("InitializeCardInfo", new object[] {
                        request}, this.InitializeCardInfoOperationCompleted, userState);
        }
        
        private void OnInitializeCardInfoOperationCompleted(object arg) {
            if ((this.InitializeCardInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializeCardInfoCompleted(this, new InitializeCardInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/VerifyCardInfo", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardInfoResponse VerifyCardInfo(CardInfoRequest request) {
            object[] results = this.Invoke("VerifyCardInfo", new object[] {
                        request});
            return ((CardInfoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyCardInfoAsync(CardInfoRequest request) {
            this.VerifyCardInfoAsync(request, null);
        }
        
        /// <remarks/>
        public void VerifyCardInfoAsync(CardInfoRequest request, object userState) {
            if ((this.VerifyCardInfoOperationCompleted == null)) {
                this.VerifyCardInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyCardInfoOperationCompleted);
            }
            this.InvokeAsync("VerifyCardInfo", new object[] {
                        request}, this.VerifyCardInfoOperationCompleted, userState);
        }
        
        private void OnVerifyCardInfoOperationCompleted(object arg) {
            if ((this.VerifyCardInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyCardInfoCompleted(this, new VerifyCardInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/AcknowledgeCardInfo", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AcknowledgeCardInfo(CardInfoRequest request) {
            object[] results = this.Invoke("AcknowledgeCardInfo", new object[] {
                        request});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AcknowledgeCardInfoAsync(CardInfoRequest request) {
            this.AcknowledgeCardInfoAsync(request, null);
        }
        
        /// <remarks/>
        public void AcknowledgeCardInfoAsync(CardInfoRequest request, object userState) {
            if ((this.AcknowledgeCardInfoOperationCompleted == null)) {
                this.AcknowledgeCardInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcknowledgeCardInfoOperationCompleted);
            }
            this.InvokeAsync("AcknowledgeCardInfo", new object[] {
                        request}, this.AcknowledgeCardInfoOperationCompleted, userState);
        }
        
        private void OnAcknowledgeCardInfoOperationCompleted(object arg) {
            if ((this.AcknowledgeCardInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcknowledgeCardInfoCompleted(this, new AcknowledgeCardInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/UploadCSS", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CssAdminResponse UploadCSS(CssUploadRequest request) {
            object[] results = this.Invoke("UploadCSS", new object[] {
                        request});
            return ((CssAdminResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UploadCSSAsync(CssUploadRequest request) {
            this.UploadCSSAsync(request, null);
        }
        
        /// <remarks/>
        public void UploadCSSAsync(CssUploadRequest request, object userState) {
            if ((this.UploadCSSOperationCompleted == null)) {
                this.UploadCSSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadCSSOperationCompleted);
            }
            this.InvokeAsync("UploadCSS", new object[] {
                        request}, this.UploadCSSOperationCompleted, userState);
        }
        
        private void OnUploadCSSOperationCompleted(object arg) {
            if ((this.UploadCSSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadCSSCompleted(this, new UploadCSSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/DownloadCSS", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CssDownloadResponse DownloadCSS(CssDownloadRequest request) {
            object[] results = this.Invoke("DownloadCSS", new object[] {
                        request});
            return ((CssDownloadResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadCSSAsync(CssDownloadRequest request) {
            this.DownloadCSSAsync(request, null);
        }
        
        /// <remarks/>
        public void DownloadCSSAsync(CssDownloadRequest request, object userState) {
            if ((this.DownloadCSSOperationCompleted == null)) {
                this.DownloadCSSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadCSSOperationCompleted);
            }
            this.InvokeAsync("DownloadCSS", new object[] {
                        request}, this.DownloadCSSOperationCompleted, userState);
        }
        
        private void OnDownloadCSSOperationCompleted(object arg) {
            if ((this.DownloadCSSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadCSSCompleted(this, new DownloadCSSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/RemoveCSS", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CssAdminResponse RemoveCSS(CssRemoveRequest request) {
            object[] results = this.Invoke("RemoveCSS", new object[] {
                        request});
            return ((CssAdminResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveCSSAsync(CssRemoveRequest request) {
            this.RemoveCSSAsync(request, null);
        }
        
        /// <remarks/>
        public void RemoveCSSAsync(CssRemoveRequest request, object userState) {
            if ((this.RemoveCSSOperationCompleted == null)) {
                this.RemoveCSSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveCSSOperationCompleted);
            }
            this.InvokeAsync("RemoveCSS", new object[] {
                        request}, this.RemoveCSSOperationCompleted, userState);
        }
        
        private void OnRemoveCSSOperationCompleted(object arg) {
            if ((this.RemoveCSSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveCSSCompleted(this, new RemoveCSSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class InitPaymentRequest {
        
        private string merchantIDField;
        
        private string passwordField;
        
        private string invoiceField;
        
        private double totalAmountField;
        
        private double taxAmountField;
        
        private string aVSAddressField;
        
        private string aVSZipField;
        
        private string tranTypeField;
        
        private string cardHolderNameField;
        
        private string frequencyField;
        
        private string customerCodeField;
        
        private string memoField;
        
        private string processCompleteUrlField;
        
        private string returnUrlField;
        
        private string displayStyleField;
        
        private string backgroundColorField;
        
        private string fontColorField;
        
        private string fontFamilyField;
        
        private string fontSizeField;
        
        private string logoUrlField;
        
        private string pageTitleField;
        
        private string securityLogoField;
        
        private string orderTotalField;
        
        private string submitButtonTextField;
        
        private string cancelButtonTextField;
        
        private string voiceAuthCodeField;
        
        private string keypadField;
        
        private string defaultSwipeField;
        
        private string aVSFieldsField;
        
        private string partialAuthField;
        
        private string operatorIDField;
        
        private string terminalNameField;
        
        private string buttonTextColorField;
        
        private string buttonBackgroundColorField;
        
        private string jCBField;
        
        private string dinersField;
        
        private string cardEntryMethodField;
        
        private string submitButtonDefaultImageUrlField;
        
        private string submitButtonHoverImageUrlField;
        
        private string cancelButtonDefaultImageUrlField;
        
        private string cancelButtonHoverImageUrlField;
        
        private string pageTimeoutDurationField;
        
        private string pageTimeoutIndicatorField;
        
        private string cancelButtonField;
        
        private string totalAmountBackgroundColorField;
        
        private string cVVField;
        
        private string forceManualTabletField;
        
        private string laneIDField;
        
        /// <remarks/>
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
            }
        }
        
        /// <remarks/>
        public double TotalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        public double TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        public string AVSAddress {
            get {
                return this.aVSAddressField;
            }
            set {
                this.aVSAddressField = value;
            }
        }
        
        /// <remarks/>
        public string AVSZip {
            get {
                return this.aVSZipField;
            }
            set {
                this.aVSZipField = value;
            }
        }
        
        /// <remarks/>
        public string TranType {
            get {
                return this.tranTypeField;
            }
            set {
                this.tranTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
            }
        }
        
        /// <remarks/>
        public string Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessCompleteUrl {
            get {
                return this.processCompleteUrlField;
            }
            set {
                this.processCompleteUrlField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnUrl {
            get {
                return this.returnUrlField;
            }
            set {
                this.returnUrlField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayStyle {
            get {
                return this.displayStyleField;
            }
            set {
                this.displayStyleField = value;
            }
        }
        
        /// <remarks/>
        public string BackgroundColor {
            get {
                return this.backgroundColorField;
            }
            set {
                this.backgroundColorField = value;
            }
        }
        
        /// <remarks/>
        public string FontColor {
            get {
                return this.fontColorField;
            }
            set {
                this.fontColorField = value;
            }
        }
        
        /// <remarks/>
        public string FontFamily {
            get {
                return this.fontFamilyField;
            }
            set {
                this.fontFamilyField = value;
            }
        }
        
        /// <remarks/>
        public string FontSize {
            get {
                return this.fontSizeField;
            }
            set {
                this.fontSizeField = value;
            }
        }
        
        /// <remarks/>
        public string LogoUrl {
            get {
                return this.logoUrlField;
            }
            set {
                this.logoUrlField = value;
            }
        }
        
        /// <remarks/>
        public string PageTitle {
            get {
                return this.pageTitleField;
            }
            set {
                this.pageTitleField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityLogo {
            get {
                return this.securityLogoField;
            }
            set {
                this.securityLogoField = value;
            }
        }
        
        /// <remarks/>
        public string OrderTotal {
            get {
                return this.orderTotalField;
            }
            set {
                this.orderTotalField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitButtonText {
            get {
                return this.submitButtonTextField;
            }
            set {
                this.submitButtonTextField = value;
            }
        }
        
        /// <remarks/>
        public string CancelButtonText {
            get {
                return this.cancelButtonTextField;
            }
            set {
                this.cancelButtonTextField = value;
            }
        }
        
        /// <remarks/>
        public string VoiceAuthCode {
            get {
                return this.voiceAuthCodeField;
            }
            set {
                this.voiceAuthCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Keypad {
            get {
                return this.keypadField;
            }
            set {
                this.keypadField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultSwipe {
            get {
                return this.defaultSwipeField;
            }
            set {
                this.defaultSwipeField = value;
            }
        }
        
        /// <remarks/>
        public string AVSFields {
            get {
                return this.aVSFieldsField;
            }
            set {
                this.aVSFieldsField = value;
            }
        }
        
        /// <remarks/>
        public string PartialAuth {
            get {
                return this.partialAuthField;
            }
            set {
                this.partialAuthField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
            }
        }
        
        /// <remarks/>
        public string TerminalName {
            get {
                return this.terminalNameField;
            }
            set {
                this.terminalNameField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonTextColor {
            get {
                return this.buttonTextColorField;
            }
            set {
                this.buttonTextColorField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonBackgroundColor {
            get {
                return this.buttonBackgroundColorField;
            }
            set {
                this.buttonBackgroundColorField = value;
            }
        }
        
        /// <remarks/>
        public string JCB {
            get {
                return this.jCBField;
            }
            set {
                this.jCBField = value;
            }
        }
        
        /// <remarks/>
        public string Diners {
            get {
                return this.dinersField;
            }
            set {
                this.dinersField = value;
            }
        }
        
        /// <remarks/>
        public string CardEntryMethod {
            get {
                return this.cardEntryMethodField;
            }
            set {
                this.cardEntryMethodField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitButtonDefaultImageUrl {
            get {
                return this.submitButtonDefaultImageUrlField;
            }
            set {
                this.submitButtonDefaultImageUrlField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitButtonHoverImageUrl {
            get {
                return this.submitButtonHoverImageUrlField;
            }
            set {
                this.submitButtonHoverImageUrlField = value;
            }
        }
        
        /// <remarks/>
        public string CancelButtonDefaultImageUrl {
            get {
                return this.cancelButtonDefaultImageUrlField;
            }
            set {
                this.cancelButtonDefaultImageUrlField = value;
            }
        }
        
        /// <remarks/>
        public string CancelButtonHoverImageUrl {
            get {
                return this.cancelButtonHoverImageUrlField;
            }
            set {
                this.cancelButtonHoverImageUrlField = value;
            }
        }
        
        /// <remarks/>
        public string PageTimeoutDuration {
            get {
                return this.pageTimeoutDurationField;
            }
            set {
                this.pageTimeoutDurationField = value;
            }
        }
        
        /// <remarks/>
        public string PageTimeoutIndicator {
            get {
                return this.pageTimeoutIndicatorField;
            }
            set {
                this.pageTimeoutIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string CancelButton {
            get {
                return this.cancelButtonField;
            }
            set {
                this.cancelButtonField = value;
            }
        }
        
        /// <remarks/>
        public string TotalAmountBackgroundColor {
            get {
                return this.totalAmountBackgroundColorField;
            }
            set {
                this.totalAmountBackgroundColorField = value;
            }
        }
        
        /// <remarks/>
        public string CVV {
            get {
                return this.cVVField;
            }
            set {
                this.cVVField = value;
            }
        }
        
        /// <remarks/>
        public string ForceManualTablet {
            get {
                return this.forceManualTabletField;
            }
            set {
                this.forceManualTabletField = value;
            }
        }
        
        /// <remarks/>
        public string LaneID {
            get {
                return this.laneIDField;
            }
            set {
                this.laneIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CssRemoveRequest {
        
        private string merchantIDField;
        
        private string passwordField;
        
        /// <remarks/>
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CssDownloadResponse {
        
        private int responseCodeField;
        
        private string messageField;
        
        private string cssField;
        
        /// <remarks/>
        public int ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Css {
            get {
                return this.cssField;
            }
            set {
                this.cssField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CssDownloadRequest {
        
        private string merchantIDField;
        
        private string passwordField;
        
        private string formattingField;
        
        /// <remarks/>
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Formatting {
            get {
                return this.formattingField;
            }
            set {
                this.formattingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CssAdminResponse {
        
        private int responseCodeField;
        
        private string messageField;
        
        /// <remarks/>
        public int ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CssUploadRequest {
        
        private string merchantIDField;
        
        private string passwordField;
        
        private string cssField;
        
        /// <remarks/>
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Css {
            get {
                return this.cssField;
            }
            set {
                this.cssField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CardInfoResponse {
        
        private int responseCodeField;
        
        private string statusField;
        
        private string statusMessageField;
        
        private string displayMessageField;
        
        private string tokenField;
        
        private string cardTypeField;
        
        private string maskedAccountField;
        
        private string tranTypeField;
        
        private string cardUsageField;
        
        private bool cardIDExpiredField;
        
        private string cardHolderNameField;
        
        private string operatorIDField;
        
        private string expDateField;
        
        /// <remarks/>
        public int ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayMessage {
            get {
                return this.displayMessageField;
            }
            set {
                this.displayMessageField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        public string MaskedAccount {
            get {
                return this.maskedAccountField;
            }
            set {
                this.maskedAccountField = value;
            }
        }
        
        /// <remarks/>
        public string TranType {
            get {
                return this.tranTypeField;
            }
            set {
                this.tranTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CardUsage {
            get {
                return this.cardUsageField;
            }
            set {
                this.cardUsageField = value;
            }
        }
        
        /// <remarks/>
        public bool CardIDExpired {
            get {
                return this.cardIDExpiredField;
            }
            set {
                this.cardIDExpiredField = value;
            }
        }
        
        /// <remarks/>
        public string CardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
            }
        }
        
        /// <remarks/>
        public string ExpDate {
            get {
                return this.expDateField;
            }
            set {
                this.expDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CardInfoRequest {
        
        private string merchantIDField;
        
        private string passwordField;
        
        private string cardIDField;
        
        /// <remarks/>
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string CardID {
            get {
                return this.cardIDField;
            }
            set {
                this.cardIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class InitCardInfoResponse {
        
        private int responseCodeField;
        
        private string cardIDField;
        
        private string messageField;
        
        /// <remarks/>
        public int ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CardID {
            get {
                return this.cardIDField;
            }
            set {
                this.cardIDField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class InitCardInfoRequest {
        
        private string merchantIDField;
        
        private string passwordField;
        
        private string frequencyField;
        
        private string processCompleteUrlField;
        
        private string returnUrlField;
        
        private string displayStyleField;
        
        private string backgroundColorField;
        
        private string fontColorField;
        
        private string fontFamilyField;
        
        private string fontSizeField;
        
        private string logoUrlField;
        
        private string pageTitleField;
        
        private string securityLogoField;
        
        private string submitButtonTextField;
        
        private string cancelButtonTextField;
        
        private string keypadField;
        
        private string defaultSwipeField;
        
        private string cardHolderNameField;
        
        private string operatorIDField;
        
        private string buttonBackgroundColorField;
        
        private string buttonTextColorField;
        
        private string jCBField;
        
        private string dinersField;
        
        private string cardEntryMethodField;
        
        private string submitButtonDefaultImageUrlField;
        
        private string submitButtonHoverImageUrlField;
        
        private string cancelButtonDefaultImageUrlField;
        
        private string cancelButtonHoverImageUrlField;
        
        private string pageTimeoutDurationField;
        
        private string cancelButtonField;
        
        private string forceManualTabletField;
        
        private string laneIDField;
        
        /// <remarks/>
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessCompleteUrl {
            get {
                return this.processCompleteUrlField;
            }
            set {
                this.processCompleteUrlField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnUrl {
            get {
                return this.returnUrlField;
            }
            set {
                this.returnUrlField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayStyle {
            get {
                return this.displayStyleField;
            }
            set {
                this.displayStyleField = value;
            }
        }
        
        /// <remarks/>
        public string BackgroundColor {
            get {
                return this.backgroundColorField;
            }
            set {
                this.backgroundColorField = value;
            }
        }
        
        /// <remarks/>
        public string FontColor {
            get {
                return this.fontColorField;
            }
            set {
                this.fontColorField = value;
            }
        }
        
        /// <remarks/>
        public string FontFamily {
            get {
                return this.fontFamilyField;
            }
            set {
                this.fontFamilyField = value;
            }
        }
        
        /// <remarks/>
        public string FontSize {
            get {
                return this.fontSizeField;
            }
            set {
                this.fontSizeField = value;
            }
        }
        
        /// <remarks/>
        public string LogoUrl {
            get {
                return this.logoUrlField;
            }
            set {
                this.logoUrlField = value;
            }
        }
        
        /// <remarks/>
        public string PageTitle {
            get {
                return this.pageTitleField;
            }
            set {
                this.pageTitleField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityLogo {
            get {
                return this.securityLogoField;
            }
            set {
                this.securityLogoField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitButtonText {
            get {
                return this.submitButtonTextField;
            }
            set {
                this.submitButtonTextField = value;
            }
        }
        
        /// <remarks/>
        public string CancelButtonText {
            get {
                return this.cancelButtonTextField;
            }
            set {
                this.cancelButtonTextField = value;
            }
        }
        
        /// <remarks/>
        public string Keypad {
            get {
                return this.keypadField;
            }
            set {
                this.keypadField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultSwipe {
            get {
                return this.defaultSwipeField;
            }
            set {
                this.defaultSwipeField = value;
            }
        }
        
        /// <remarks/>
        public string CardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonBackgroundColor {
            get {
                return this.buttonBackgroundColorField;
            }
            set {
                this.buttonBackgroundColorField = value;
            }
        }
        
        /// <remarks/>
        public string ButtonTextColor {
            get {
                return this.buttonTextColorField;
            }
            set {
                this.buttonTextColorField = value;
            }
        }
        
        /// <remarks/>
        public string JCB {
            get {
                return this.jCBField;
            }
            set {
                this.jCBField = value;
            }
        }
        
        /// <remarks/>
        public string Diners {
            get {
                return this.dinersField;
            }
            set {
                this.dinersField = value;
            }
        }
        
        /// <remarks/>
        public string CardEntryMethod {
            get {
                return this.cardEntryMethodField;
            }
            set {
                this.cardEntryMethodField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitButtonDefaultImageUrl {
            get {
                return this.submitButtonDefaultImageUrlField;
            }
            set {
                this.submitButtonDefaultImageUrlField = value;
            }
        }
        
        /// <remarks/>
        public string SubmitButtonHoverImageUrl {
            get {
                return this.submitButtonHoverImageUrlField;
            }
            set {
                this.submitButtonHoverImageUrlField = value;
            }
        }
        
        /// <remarks/>
        public string CancelButtonDefaultImageUrl {
            get {
                return this.cancelButtonDefaultImageUrlField;
            }
            set {
                this.cancelButtonDefaultImageUrlField = value;
            }
        }
        
        /// <remarks/>
        public string CancelButtonHoverImageUrl {
            get {
                return this.cancelButtonHoverImageUrlField;
            }
            set {
                this.cancelButtonHoverImageUrlField = value;
            }
        }
        
        /// <remarks/>
        public string PageTimeoutDuration {
            get {
                return this.pageTimeoutDurationField;
            }
            set {
                this.pageTimeoutDurationField = value;
            }
        }
        
        /// <remarks/>
        public string CancelButton {
            get {
                return this.cancelButtonField;
            }
            set {
                this.cancelButtonField = value;
            }
        }
        
        /// <remarks/>
        public string ForceManualTablet {
            get {
                return this.forceManualTabletField;
            }
            set {
                this.forceManualTabletField = value;
            }
        }
        
        /// <remarks/>
        public string LaneID {
            get {
                return this.laneIDField;
            }
            set {
                this.laneIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class PaymentInfoResponse {
        
        private int responseCodeField;
        
        private string statusField;
        
        private string statusMessageField;
        
        private string displayMessageField;
        
        private string avsResultField;
        
        private string cvvResultField;
        
        private string authCodeField;
        
        private string tokenField;
        
        private string refNoField;
        
        private string invoiceField;
        
        private string acqRefDataField;
        
        private string cardTypeField;
        
        private string maskedAccountField;
        
        private double amountField;
        
        private double taxAmountField;
        
        private System.DateTime transPostTimeField;
        
        private string cardholderNameField;
        
        private string aVSAddressField;
        
        private string aVSZipField;
        
        private string tranTypeField;
        
        private bool paymentIDExpiredField;
        
        private string customerCodeField;
        
        private string memoField;
        
        private double authAmountField;
        
        private string voiceAuthCodeField;
        
        private string processDataField;
        
        private string operatorIDField;
        
        private string terminalNameField;
        
        private string expDateField;
        
        /// <remarks/>
        public int ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayMessage {
            get {
                return this.displayMessageField;
            }
            set {
                this.displayMessageField = value;
            }
        }
        
        /// <remarks/>
        public string AvsResult {
            get {
                return this.avsResultField;
            }
            set {
                this.avsResultField = value;
            }
        }
        
        /// <remarks/>
        public string CvvResult {
            get {
                return this.cvvResultField;
            }
            set {
                this.cvvResultField = value;
            }
        }
        
        /// <remarks/>
        public string AuthCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string RefNo {
            get {
                return this.refNoField;
            }
            set {
                this.refNoField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
            }
        }
        
        /// <remarks/>
        public string AcqRefData {
            get {
                return this.acqRefDataField;
            }
            set {
                this.acqRefDataField = value;
            }
        }
        
        /// <remarks/>
        public string CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        public string MaskedAccount {
            get {
                return this.maskedAccountField;
            }
            set {
                this.maskedAccountField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public double TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransPostTime {
            get {
                return this.transPostTimeField;
            }
            set {
                this.transPostTimeField = value;
            }
        }
        
        /// <remarks/>
        public string CardholderName {
            get {
                return this.cardholderNameField;
            }
            set {
                this.cardholderNameField = value;
            }
        }
        
        /// <remarks/>
        public string AVSAddress {
            get {
                return this.aVSAddressField;
            }
            set {
                this.aVSAddressField = value;
            }
        }
        
        /// <remarks/>
        public string AVSZip {
            get {
                return this.aVSZipField;
            }
            set {
                this.aVSZipField = value;
            }
        }
        
        /// <remarks/>
        public string TranType {
            get {
                return this.tranTypeField;
            }
            set {
                this.tranTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool PaymentIDExpired {
            get {
                return this.paymentIDExpiredField;
            }
            set {
                this.paymentIDExpiredField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
            }
        }
        
        /// <remarks/>
        public double AuthAmount {
            get {
                return this.authAmountField;
            }
            set {
                this.authAmountField = value;
            }
        }
        
        /// <remarks/>
        public string VoiceAuthCode {
            get {
                return this.voiceAuthCodeField;
            }
            set {
                this.voiceAuthCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProcessData {
            get {
                return this.processDataField;
            }
            set {
                this.processDataField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
            }
        }
        
        /// <remarks/>
        public string TerminalName {
            get {
                return this.terminalNameField;
            }
            set {
                this.terminalNameField = value;
            }
        }
        
        /// <remarks/>
        public string ExpDate {
            get {
                return this.expDateField;
            }
            set {
                this.expDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class PaymentInfoRequest {
        
        private string merchantIDField;
        
        private string passwordField;
        
        private string paymentIDField;
        
        /// <remarks/>
        public string MerchantID {
            get {
                return this.merchantIDField;
            }
            set {
                this.merchantIDField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentID {
            get {
                return this.paymentIDField;
            }
            set {
                this.paymentIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class InitPaymentResponse {
        
        private int responseCodeField;
        
        private string paymentIDField;
        
        private string messageField;
        
        /// <remarks/>
        public int ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentID {
            get {
                return this.paymentIDField;
            }
            set {
                this.paymentIDField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void InitializePaymentCompletedEventHandler(object sender, InitializePaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitializePaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitializePaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InitPaymentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InitPaymentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void VerifyPaymentCompletedEventHandler(object sender, VerifyPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PaymentInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PaymentInfoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AcknowledgePaymentCompletedEventHandler(object sender, AcknowledgePaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AcknowledgePaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AcknowledgePaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void InitializeCardInfoCompletedEventHandler(object sender, InitializeCardInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitializeCardInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitializeCardInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InitCardInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InitCardInfoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void VerifyCardInfoCompletedEventHandler(object sender, VerifyCardInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyCardInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyCardInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardInfoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AcknowledgeCardInfoCompletedEventHandler(object sender, AcknowledgeCardInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AcknowledgeCardInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AcknowledgeCardInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UploadCSSCompletedEventHandler(object sender, UploadCSSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadCSSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadCSSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CssAdminResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CssAdminResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DownloadCSSCompletedEventHandler(object sender, DownloadCSSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadCSSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadCSSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CssDownloadResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CssDownloadResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RemoveCSSCompletedEventHandler(object sender, RemoveCSSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveCSSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveCSSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CssAdminResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CssAdminResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591