// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Mise.Inventory.Android.MercuryWebService {
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name="HCServiceSoap", Namespace="http://www.mercurypay.com/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HCService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InitializePaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcknowledgePaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitializeCardInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyCardInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcknowledgeCardInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadCSSOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadCSSOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveCSSOperationCompleted;
        
        public HCService() {
            this.Url = "https://hc.mercurydev.net/hcws/hcservice.asmx";
        }
        
        public HCService(string url) {
            this.Url = url;
        }
        
        public event InitializePaymentCompletedEventHandler InitializePaymentCompleted;
        
        public event VerifyPaymentCompletedEventHandler VerifyPaymentCompleted;
        
        public event AcknowledgePaymentCompletedEventHandler AcknowledgePaymentCompleted;
        
        public event InitializeCardInfoCompletedEventHandler InitializeCardInfoCompleted;
        
        public event VerifyCardInfoCompletedEventHandler VerifyCardInfoCompleted;
        
        public event AcknowledgeCardInfoCompletedEventHandler AcknowledgeCardInfoCompleted;
        
        public event UploadCSSCompletedEventHandler UploadCSSCompleted;
        
        public event DownloadCSSCompletedEventHandler DownloadCSSCompleted;
        
        public event RemoveCSSCompletedEventHandler RemoveCSSCompleted;
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/InitializePayment", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public InitPaymentResponse InitializePayment(InitPaymentRequest request) {
            object[] results = this.Invoke("InitializePayment", new object[] {
                        request});
            return ((InitPaymentResponse)(results[0]));
        }
        
        public System.IAsyncResult BeginInitializePayment(InitPaymentRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InitializePayment", new object[] {
                        request}, callback, asyncState);
        }
        
        public InitPaymentResponse EndInitializePayment(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((InitPaymentResponse)(results[0]));
        }
        
        public void InitializePaymentAsync(InitPaymentRequest request) {
            this.InitializePaymentAsync(request, null);
        }
        
        public void InitializePaymentAsync(InitPaymentRequest request, object userState) {
            if ((this.InitializePaymentOperationCompleted == null)) {
                this.InitializePaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializePaymentCompleted);
            }
            this.InvokeAsync("InitializePayment", new object[] {
                        request}, this.InitializePaymentOperationCompleted, userState);
        }
        
        private void OnInitializePaymentCompleted(object arg) {
            if ((this.InitializePaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializePaymentCompleted(this, new InitializePaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/VerifyPayment", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public PaymentInfoResponse VerifyPayment(PaymentInfoRequest request) {
            object[] results = this.Invoke("VerifyPayment", new object[] {
                        request});
            return ((PaymentInfoResponse)(results[0]));
        }
        
        public System.IAsyncResult BeginVerifyPayment(PaymentInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("VerifyPayment", new object[] {
                        request}, callback, asyncState);
        }
        
        public PaymentInfoResponse EndVerifyPayment(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PaymentInfoResponse)(results[0]));
        }
        
        public void VerifyPaymentAsync(PaymentInfoRequest request) {
            this.VerifyPaymentAsync(request, null);
        }
        
        public void VerifyPaymentAsync(PaymentInfoRequest request, object userState) {
            if ((this.VerifyPaymentOperationCompleted == null)) {
                this.VerifyPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyPaymentCompleted);
            }
            this.InvokeAsync("VerifyPayment", new object[] {
                        request}, this.VerifyPaymentOperationCompleted, userState);
        }
        
        private void OnVerifyPaymentCompleted(object arg) {
            if ((this.VerifyPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyPaymentCompleted(this, new VerifyPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/AcknowledgePayment", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public int AcknowledgePayment(PaymentInfoRequest request) {
            object[] results = this.Invoke("AcknowledgePayment", new object[] {
                        request});
            return ((int)(results[0]));
        }
        
        public System.IAsyncResult BeginAcknowledgePayment(PaymentInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AcknowledgePayment", new object[] {
                        request}, callback, asyncState);
        }
        
        public int EndAcknowledgePayment(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        public void AcknowledgePaymentAsync(PaymentInfoRequest request) {
            this.AcknowledgePaymentAsync(request, null);
        }
        
        public void AcknowledgePaymentAsync(PaymentInfoRequest request, object userState) {
            if ((this.AcknowledgePaymentOperationCompleted == null)) {
                this.AcknowledgePaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcknowledgePaymentCompleted);
            }
            this.InvokeAsync("AcknowledgePayment", new object[] {
                        request}, this.AcknowledgePaymentOperationCompleted, userState);
        }
        
        private void OnAcknowledgePaymentCompleted(object arg) {
            if ((this.AcknowledgePaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcknowledgePaymentCompleted(this, new AcknowledgePaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/InitializeCardInfo", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public InitCardInfoResponse InitializeCardInfo(InitCardInfoRequest request) {
            object[] results = this.Invoke("InitializeCardInfo", new object[] {
                        request});
            return ((InitCardInfoResponse)(results[0]));
        }
        
        public System.IAsyncResult BeginInitializeCardInfo(InitCardInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InitializeCardInfo", new object[] {
                        request}, callback, asyncState);
        }
        
        public InitCardInfoResponse EndInitializeCardInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((InitCardInfoResponse)(results[0]));
        }
        
        public void InitializeCardInfoAsync(InitCardInfoRequest request) {
            this.InitializeCardInfoAsync(request, null);
        }
        
        public void InitializeCardInfoAsync(InitCardInfoRequest request, object userState) {
            if ((this.InitializeCardInfoOperationCompleted == null)) {
                this.InitializeCardInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeCardInfoCompleted);
            }
            this.InvokeAsync("InitializeCardInfo", new object[] {
                        request}, this.InitializeCardInfoOperationCompleted, userState);
        }
        
        private void OnInitializeCardInfoCompleted(object arg) {
            if ((this.InitializeCardInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializeCardInfoCompleted(this, new InitializeCardInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/VerifyCardInfo", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public CardInfoResponse VerifyCardInfo(CardInfoRequest request) {
            object[] results = this.Invoke("VerifyCardInfo", new object[] {
                        request});
            return ((CardInfoResponse)(results[0]));
        }
        
        public System.IAsyncResult BeginVerifyCardInfo(CardInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("VerifyCardInfo", new object[] {
                        request}, callback, asyncState);
        }
        
        public CardInfoResponse EndVerifyCardInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CardInfoResponse)(results[0]));
        }
        
        public void VerifyCardInfoAsync(CardInfoRequest request) {
            this.VerifyCardInfoAsync(request, null);
        }
        
        public void VerifyCardInfoAsync(CardInfoRequest request, object userState) {
            if ((this.VerifyCardInfoOperationCompleted == null)) {
                this.VerifyCardInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyCardInfoCompleted);
            }
            this.InvokeAsync("VerifyCardInfo", new object[] {
                        request}, this.VerifyCardInfoOperationCompleted, userState);
        }
        
        private void OnVerifyCardInfoCompleted(object arg) {
            if ((this.VerifyCardInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyCardInfoCompleted(this, new VerifyCardInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/AcknowledgeCardInfo", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public int AcknowledgeCardInfo(CardInfoRequest request) {
            object[] results = this.Invoke("AcknowledgeCardInfo", new object[] {
                        request});
            return ((int)(results[0]));
        }
        
        public System.IAsyncResult BeginAcknowledgeCardInfo(CardInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AcknowledgeCardInfo", new object[] {
                        request}, callback, asyncState);
        }
        
        public int EndAcknowledgeCardInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        public void AcknowledgeCardInfoAsync(CardInfoRequest request) {
            this.AcknowledgeCardInfoAsync(request, null);
        }
        
        public void AcknowledgeCardInfoAsync(CardInfoRequest request, object userState) {
            if ((this.AcknowledgeCardInfoOperationCompleted == null)) {
                this.AcknowledgeCardInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcknowledgeCardInfoCompleted);
            }
            this.InvokeAsync("AcknowledgeCardInfo", new object[] {
                        request}, this.AcknowledgeCardInfoOperationCompleted, userState);
        }
        
        private void OnAcknowledgeCardInfoCompleted(object arg) {
            if ((this.AcknowledgeCardInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcknowledgeCardInfoCompleted(this, new AcknowledgeCardInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/UploadCSS", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public CssAdminResponse UploadCSS(CssUploadRequest request) {
            object[] results = this.Invoke("UploadCSS", new object[] {
                        request});
            return ((CssAdminResponse)(results[0]));
        }
        
        public System.IAsyncResult BeginUploadCSS(CssUploadRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UploadCSS", new object[] {
                        request}, callback, asyncState);
        }
        
        public CssAdminResponse EndUploadCSS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CssAdminResponse)(results[0]));
        }
        
        public void UploadCSSAsync(CssUploadRequest request) {
            this.UploadCSSAsync(request, null);
        }
        
        public void UploadCSSAsync(CssUploadRequest request, object userState) {
            if ((this.UploadCSSOperationCompleted == null)) {
                this.UploadCSSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadCSSCompleted);
            }
            this.InvokeAsync("UploadCSS", new object[] {
                        request}, this.UploadCSSOperationCompleted, userState);
        }
        
        private void OnUploadCSSCompleted(object arg) {
            if ((this.UploadCSSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadCSSCompleted(this, new UploadCSSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/DownloadCSS", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public CssDownloadResponse DownloadCSS(CssDownloadRequest request) {
            object[] results = this.Invoke("DownloadCSS", new object[] {
                        request});
            return ((CssDownloadResponse)(results[0]));
        }
        
        public System.IAsyncResult BeginDownloadCSS(CssDownloadRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DownloadCSS", new object[] {
                        request}, callback, asyncState);
        }
        
        public CssDownloadResponse EndDownloadCSS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CssDownloadResponse)(results[0]));
        }
        
        public void DownloadCSSAsync(CssDownloadRequest request) {
            this.DownloadCSSAsync(request, null);
        }
        
        public void DownloadCSSAsync(CssDownloadRequest request, object userState) {
            if ((this.DownloadCSSOperationCompleted == null)) {
                this.DownloadCSSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadCSSCompleted);
            }
            this.InvokeAsync("DownloadCSS", new object[] {
                        request}, this.DownloadCSSOperationCompleted, userState);
        }
        
        private void OnDownloadCSSCompleted(object arg) {
            if ((this.DownloadCSSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadCSSCompleted(this, new DownloadCSSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mercurypay.com/RemoveCSS", RequestNamespace="http://www.mercurypay.com/", ResponseNamespace="http://www.mercurypay.com/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public CssAdminResponse RemoveCSS(CssRemoveRequest request) {
            object[] results = this.Invoke("RemoveCSS", new object[] {
                        request});
            return ((CssAdminResponse)(results[0]));
        }
        
        public System.IAsyncResult BeginRemoveCSS(CssRemoveRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RemoveCSS", new object[] {
                        request}, callback, asyncState);
        }
        
        public CssAdminResponse EndRemoveCSS(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CssAdminResponse)(results[0]));
        }
        
        public void RemoveCSSAsync(CssRemoveRequest request) {
            this.RemoveCSSAsync(request, null);
        }
        
        public void RemoveCSSAsync(CssRemoveRequest request, object userState) {
            if ((this.RemoveCSSOperationCompleted == null)) {
                this.RemoveCSSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveCSSCompleted);
            }
            this.InvokeAsync("RemoveCSS", new object[] {
                        request}, this.RemoveCSSOperationCompleted, userState);
        }
        
        private void OnRemoveCSSCompleted(object arg) {
            if ((this.RemoveCSSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveCSSCompleted(this, new RemoveCSSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class InitPaymentRequest {
        
        /// <remarks/>
        public string MerchantID;
        
        /// <remarks/>
        public string Password;
        
        /// <remarks/>
        public string Invoice;
        
        /// <remarks/>
        public double TotalAmount;
        
        /// <remarks/>
        public double TaxAmount;
        
        /// <remarks/>
        public string AVSAddress;
        
        /// <remarks/>
        public string AVSZip;
        
        /// <remarks/>
        public string TranType;
        
        /// <remarks/>
        public string CardHolderName;
        
        /// <remarks/>
        public string Frequency;
        
        /// <remarks/>
        public string CustomerCode;
        
        /// <remarks/>
        public string Memo;
        
        /// <remarks/>
        public string ProcessCompleteUrl;
        
        /// <remarks/>
        public string ReturnUrl;
        
        /// <remarks/>
        public string DisplayStyle;
        
        /// <remarks/>
        public string BackgroundColor;
        
        /// <remarks/>
        public string FontColor;
        
        /// <remarks/>
        public string FontFamily;
        
        /// <remarks/>
        public string FontSize;
        
        /// <remarks/>
        public string LogoUrl;
        
        /// <remarks/>
        public string PageTitle;
        
        /// <remarks/>
        public string SecurityLogo;
        
        /// <remarks/>
        public string OrderTotal;
        
        /// <remarks/>
        public string SubmitButtonText;
        
        /// <remarks/>
        public string CancelButtonText;
        
        /// <remarks/>
        public string VoiceAuthCode;
        
        /// <remarks/>
        public string Keypad;
        
        /// <remarks/>
        public string DefaultSwipe;
        
        /// <remarks/>
        public string AVSFields;
        
        /// <remarks/>
        public string PartialAuth;
        
        /// <remarks/>
        public string OperatorID;
        
        /// <remarks/>
        public string TerminalName;
        
        /// <remarks/>
        public string ButtonTextColor;
        
        /// <remarks/>
        public string ButtonBackgroundColor;
        
        /// <remarks/>
        public string JCB;
        
        /// <remarks/>
        public string Diners;
        
        /// <remarks/>
        public string CardEntryMethod;
        
        /// <remarks/>
        public string SubmitButtonDefaultImageUrl;
        
        /// <remarks/>
        public string SubmitButtonHoverImageUrl;
        
        /// <remarks/>
        public string CancelButtonDefaultImageUrl;
        
        /// <remarks/>
        public string CancelButtonHoverImageUrl;
        
        /// <remarks/>
        public string PageTimeoutDuration;
        
        /// <remarks/>
        public string PageTimeoutIndicator;
        
        /// <remarks/>
        public string CancelButton;
        
        /// <remarks/>
        public string TotalAmountBackgroundColor;
        
        /// <remarks/>
        public string CVV;
        
        /// <remarks/>
        public string ForceManualTablet;
        
        /// <remarks/>
        public string LaneID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class InitPaymentResponse {
        
        /// <remarks/>
        public int ResponseCode;
        
        /// <remarks/>
        public string PaymentID;
        
        /// <remarks/>
        public string Message;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class PaymentInfoRequest {
        
        /// <remarks/>
        public string MerchantID;
        
        /// <remarks/>
        public string Password;
        
        /// <remarks/>
        public string PaymentID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class PaymentInfoResponse {
        
        /// <remarks/>
        public int ResponseCode;
        
        /// <remarks/>
        public string Status;
        
        /// <remarks/>
        public string StatusMessage;
        
        /// <remarks/>
        public string DisplayMessage;
        
        /// <remarks/>
        public string AvsResult;
        
        /// <remarks/>
        public string CvvResult;
        
        /// <remarks/>
        public string AuthCode;
        
        /// <remarks/>
        public string Token;
        
        /// <remarks/>
        public string RefNo;
        
        /// <remarks/>
        public string Invoice;
        
        /// <remarks/>
        public string AcqRefData;
        
        /// <remarks/>
        public string CardType;
        
        /// <remarks/>
        public string MaskedAccount;
        
        /// <remarks/>
        public double Amount;
        
        /// <remarks/>
        public double TaxAmount;
        
        /// <remarks/>
        public System.DateTime TransPostTime;
        
        /// <remarks/>
        public string CardholderName;
        
        /// <remarks/>
        public string AVSAddress;
        
        /// <remarks/>
        public string AVSZip;
        
        /// <remarks/>
        public string TranType;
        
        /// <remarks/>
        public bool PaymentIDExpired;
        
        /// <remarks/>
        public string CustomerCode;
        
        /// <remarks/>
        public string Memo;
        
        /// <remarks/>
        public double AuthAmount;
        
        /// <remarks/>
        public string VoiceAuthCode;
        
        /// <remarks/>
        public string ProcessData;
        
        /// <remarks/>
        public string OperatorID;
        
        /// <remarks/>
        public string TerminalName;
        
        /// <remarks/>
        public string ExpDate;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class InitCardInfoRequest {
        
        /// <remarks/>
        public string MerchantID;
        
        /// <remarks/>
        public string Password;
        
        /// <remarks/>
        public string Frequency;
        
        /// <remarks/>
        public string ProcessCompleteUrl;
        
        /// <remarks/>
        public string ReturnUrl;
        
        /// <remarks/>
        public string DisplayStyle;
        
        /// <remarks/>
        public string BackgroundColor;
        
        /// <remarks/>
        public string FontColor;
        
        /// <remarks/>
        public string FontFamily;
        
        /// <remarks/>
        public string FontSize;
        
        /// <remarks/>
        public string LogoUrl;
        
        /// <remarks/>
        public string PageTitle;
        
        /// <remarks/>
        public string SecurityLogo;
        
        /// <remarks/>
        public string SubmitButtonText;
        
        /// <remarks/>
        public string CancelButtonText;
        
        /// <remarks/>
        public string Keypad;
        
        /// <remarks/>
        public string DefaultSwipe;
        
        /// <remarks/>
        public string CardHolderName;
        
        /// <remarks/>
        public string OperatorID;
        
        /// <remarks/>
        public string ButtonBackgroundColor;
        
        /// <remarks/>
        public string ButtonTextColor;
        
        /// <remarks/>
        public string JCB;
        
        /// <remarks/>
        public string Diners;
        
        /// <remarks/>
        public string CardEntryMethod;
        
        /// <remarks/>
        public string SubmitButtonDefaultImageUrl;
        
        /// <remarks/>
        public string SubmitButtonHoverImageUrl;
        
        /// <remarks/>
        public string CancelButtonDefaultImageUrl;
        
        /// <remarks/>
        public string CancelButtonHoverImageUrl;
        
        /// <remarks/>
        public string PageTimeoutDuration;
        
        /// <remarks/>
        public string CancelButton;
        
        /// <remarks/>
        public string ForceManualTablet;
        
        /// <remarks/>
        public string LaneID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class InitCardInfoResponse {
        
        /// <remarks/>
        public int ResponseCode;
        
        /// <remarks/>
        public string CardID;
        
        /// <remarks/>
        public string Message;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CardInfoRequest {
        
        /// <remarks/>
        public string MerchantID;
        
        /// <remarks/>
        public string Password;
        
        /// <remarks/>
        public string CardID;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CardInfoResponse {
        
        /// <remarks/>
        public int ResponseCode;
        
        /// <remarks/>
        public string Status;
        
        /// <remarks/>
        public string StatusMessage;
        
        /// <remarks/>
        public string DisplayMessage;
        
        /// <remarks/>
        public string Token;
        
        /// <remarks/>
        public string CardType;
        
        /// <remarks/>
        public string MaskedAccount;
        
        /// <remarks/>
        public string TranType;
        
        /// <remarks/>
        public string CardUsage;
        
        /// <remarks/>
        public bool CardIDExpired;
        
        /// <remarks/>
        public string CardHolderName;
        
        /// <remarks/>
        public string OperatorID;
        
        /// <remarks/>
        public string ExpDate;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CssUploadRequest {
        
        /// <remarks/>
        public string MerchantID;
        
        /// <remarks/>
        public string Password;
        
        /// <remarks/>
        public string Css;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CssAdminResponse {
        
        /// <remarks/>
        public int ResponseCode;
        
        /// <remarks/>
        public string Message;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CssDownloadRequest {
        
        /// <remarks/>
        public string MerchantID;
        
        /// <remarks/>
        public string Password;
        
        /// <remarks/>
        public string Formatting;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CssDownloadResponse {
        
        /// <remarks/>
        public int ResponseCode;
        
        /// <remarks/>
        public string Message;
        
        /// <remarks/>
        public string Css;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mercurypay.com/")]
    public partial class CssRemoveRequest {
        
        /// <remarks/>
        public string MerchantID;
        
        /// <remarks/>
        public string Password;
    }
    
    public partial class InitializePaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitializePaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public InitPaymentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InitPaymentResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void InitializePaymentCompletedEventHandler(object sender, InitializePaymentCompletedEventArgs args);
    
    public partial class VerifyPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PaymentInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PaymentInfoResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void VerifyPaymentCompletedEventHandler(object sender, VerifyPaymentCompletedEventArgs args);
    
    public partial class AcknowledgePaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AcknowledgePaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    public delegate void AcknowledgePaymentCompletedEventHandler(object sender, AcknowledgePaymentCompletedEventArgs args);
    
    public partial class InitializeCardInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitializeCardInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public InitCardInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InitCardInfoResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void InitializeCardInfoCompletedEventHandler(object sender, InitializeCardInfoCompletedEventArgs args);
    
    public partial class VerifyCardInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyCardInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CardInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardInfoResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void VerifyCardInfoCompletedEventHandler(object sender, VerifyCardInfoCompletedEventArgs args);
    
    public partial class AcknowledgeCardInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AcknowledgeCardInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    public delegate void AcknowledgeCardInfoCompletedEventHandler(object sender, AcknowledgeCardInfoCompletedEventArgs args);
    
    public partial class UploadCSSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadCSSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CssAdminResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CssAdminResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void UploadCSSCompletedEventHandler(object sender, UploadCSSCompletedEventArgs args);
    
    public partial class DownloadCSSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadCSSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CssDownloadResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CssDownloadResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void DownloadCSSCompletedEventHandler(object sender, DownloadCSSCompletedEventArgs args);
    
    public partial class RemoveCSSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveCSSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CssAdminResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CssAdminResponse)(this.results[0]));
            }
        }
    }
    
    public delegate void RemoveCSSCompletedEventHandler(object sender, RemoveCSSCompletedEventArgs args);
}
